name: Project Name
title: Picketlink - Apached Licensed Open Source Java Security
org: Organization
base_url: http://localhost:4242/

jborg_js_url: http://static.jboss.org/theme/js
jborg_images_url: http://static.jboss.org/theme/images